general:
  env: dev
  name: github.com/neo532/kratos_layout
  logger:
    level: debug
    filename: ./log/business.log
    max_size: 10
    max_backup: 5
    max_age: 7
    compress: false
    filename_script: ./log/script.log
    filename_consumer: ./log/consumer.log
    filename_test: ./log/test.log


server:
  http:
    addr: 0.0.0.0:8500
    timeout: 3s


data:
  database_default:
    conf:
      max_open_conns: 2
      max_idle_conns: 2
      conn_max_lifetime: 2s
      max_slowtime: 0.5s
      table_prefix: 
      read:
        name: "default_read"
        dsn: root:password@tcp(test.domain:3306)/dbName?charset=utf8mb4&parseTime=true&loc=Local
      write:
        name: "default_write"
        dsn: root:password@tcp(test.domain:3306)/dbName?charset=utf8mb4&parseTime=true&loc=Local



  redis_lock:
    conf:
      max_slowtime: 0.5s
      default:
        name: lock
        db: 0
        addr: test.domain:6379
        password: password


third:
  sample:
    domain: https://scrm-wx.weiling.cn
