triggers:
- name: cmd/script
  pattens:
  - '**/*.go'
  env:
    DEBUG: "1"
  cmd: go build -o ./bin/ ./cmd/script && ./bin/script -conf configs/config.yaml -cmd CalulateRank -args '2023-09-24'
  #cmd: go build -o ./bin/ ./cmd/script && ./bin/script -conf configs/config.yaml -cmd SyncUserByUserID -args 'aaaa,bbb'
  shell: true
  delay: 100ms
  stop_timeout: 500ms
  signal: KILL
  kill_signal: "SIGTERM"
watch_paths:
- .
watch_depth: 5
